#ifndef DHCP_H
#define DHCP_H
#include "io.h"
#include "net.h"
#include "udp.h"
#include "nic.h"
#include "serial.h"
#include "netclock.h"

/* ============================================================
 * dhcp.h -- DHCP: the reason this OS can plug into literally any modern
 * network and get an address, instead of hardcoding 10.0.2.15 forever
 * and only ever working inside one specific QEMU invocation. This is
 * the single biggest unlock for "compatible with modern networks" of
 * anything in this file.
 *
 * The dance is four packets, universally remembered by the acronym
 * DORA: Discover (us, shouting "anyone got a spare IP?" to the whole
 * subnet), Offer (a server replying "yes, have this one"), Request (us,
 * confirming "okay, I'll take it" -- said out loud so *other* DHCP
 * servers who also made offers know to withdraw theirs), and Ack (the
 * server confirming the lease is really ours). We implement exactly
 * this happy path, and (since rc-3) the lease lifecycle that follows it:
 * the lease time is kept, the address is renewed at T1 (half the lease,
 * unicast to the server), rebound at T2 (7/8, broadcast), and dropped if
 * the lease runs out -- an address held past its lease is an address
 * the server may already have handed to somebody else.
 * ============================================================ */

#define DHCP_CLIENT_PORT 68
#define DHCP_SERVER_PORT 67

#define DHCP_OP_REQUEST  1
#define DHCP_OP_REPLY    2
#define DHCP_HTYPE_ETH   1

#define DHCP_MSG_DISCOVER 1
#define DHCP_MSG_OFFER    2
#define DHCP_MSG_REQUEST  3
#define DHCP_MSG_ACK      5
#define DHCP_MSG_NAK      6

#define DHCP_MAGIC_COOKIE 0x63825363u  /* the four bytes that mark "yes, options follow,
                                        * this isn't just BOOTP's ghost" -- baked into
                                        * the spec since RFC 1497 and never changing */

#define DHCP_OPT_PAD          0
#define DHCP_OPT_SUBNET_MASK  1
#define DHCP_OPT_ROUTER       3
#define DHCP_OPT_DNS          6
#define DHCP_OPT_REQUESTED_IP 50
#define DHCP_OPT_LEASE_TIME   51
#define DHCP_OPT_MSG_TYPE     53
#define DHCP_OPT_SERVER_ID    54
#define DHCP_OPT_PARAM_REQ    55
#define DHCP_OPT_END          255

typedef enum {
    DHCP_STATE_IDLE,
    DHCP_STATE_DISCOVER_SENT,
    DHCP_STATE_REQUEST_SENT,
    DHCP_STATE_BOUND,
    DHCP_STATE_RENEWING,     /* T1 passed: asking our own server (unicast) to extend the lease */
    DHCP_STATE_REBINDING     /* T2 passed: asking ANY server (broadcast) to extend it */
} dhcp_state_t;

static dhcp_state_t dhcp_state = DHCP_STATE_IDLE;
static u32 dhcp_offered_ip = 0;
static u32 dhcp_server_id = 0;
static u32 dhcp_last_sent_wall = 0;   /* RTC seconds-of-day of the last DISCOVER/REQUEST we sent */
static u32 dhcp_last_sent_tick = 0;
static int dhcp_tries = 0;            /* how many times we've had to resend in this conversation */
static int dhcp_started = 0;
static u32 dhcp_xid = 0x1234ABCD; /* transaction ID of the current conversation: regenerated by dhcp_new_xid() for EVERY conversation
                                   * (this initial value is never put on the wire) */

/* Lease bookkeeping. Time is the RTC (netclock.h) accumulated in whole seconds, because the RTC value is a
 * seconds-of-day that wraps at midnight and a lease can outlast a day. */
static u32 dhcp_lease_secs = 0;       /* granted lease length; 0 = no lease option seen (never expires); 0xFFFFFFFF = infinite */
static u32 dhcp_lease_age = 0;        /* seconds since the lease started */
static u32 dhcp_lease_mark = 0;       /* RTC seconds-of-day at the last time we added to dhcp_lease_age */
static u32 dhcp_lease_tick_mark = 0;  /* net_ticks at the last RTC sample (we do not read the CMOS every loop pass) */
static u32 dhcp_ciaddr = 0;           /* set by the renew/rebind senders: our current address goes in the ciaddr field */

/* A transaction id the network cannot guess. The old one started as a constant and was later derived from the
 * tick counter alone -- a handful of bits an on-link attacker can enumerate in seconds, and the xid is the
 * only thing tying a reply to our conversation. This mixes the CPU's timestamp counter, tick count, RTC
 * seconds, our MAC and the previous xid through an xorshift scrambler. It is still not cryptographic (there
 * is no real entropy source this early in boot), but it is not enumerable from a few observed packets. */
static inline u32 dhcp_new_xid(void) {
    u32 lo, hi;
    __asm__ volatile ("rdtsc" : "=a"(lo), "=d"(hi));
    u32 x = lo ^ (hi * 0x9E3779B1u) ^ (net_ticks * 2654435761u) ^ (net_wall_seconds() * 40503u) ^ (dhcp_xid * 1664525u + 1013904223u);
    for (int i = 0; i < 6; i++) x = ((x << 7) | (x >> 25)) ^ ((u32)nic.mac[i] * 0x01000193u);
    x ^= x << 13; x ^= x >> 17; x ^= x << 5;
    if (x == 0) x = 0xA5A5A5A5u;
    return x;
}

/* A DHCP packet is BOOTP's fixed 236-byte layout (mostly zeroed fields
 * this simple client doesn't use) followed by the magic cookie and then
 * a TLV option list. We build it field-by-field into a flat buffer
 * rather than defining a struct, because several fields are odd sizes
 * (a 16-byte hardware address field for a 6-byte MAC, 64 and 128 byte
 * string fields we never fill) and a packed struct buys us nothing a
 * comment doesn't already explain. */
#define DHCP_FIXED_LEN 236

static inline u16 dhcp_build_packet(u8 *out, u8 msg_type, u32 requested_ip, u32 server_id) {
    for (int i = 0; i < DHCP_FIXED_LEN; i++) out[i] = 0;

    out[0] = DHCP_OP_REQUEST;
    out[1] = DHCP_HTYPE_ETH;
    out[2] = 6;                              /* hardware address length */
    out[3] = 0;                              /* hops */
    net_put32_be(&out[4], dhcp_xid);
    net_put16_be(&out[8], 0);                /* secs elapsed: not tracked, harmless to omit */
    /* flags: broadcast bit set -- we have no IP yet, so the reply has nowhere unicast to go. A renewing client
     * (dhcp_ciaddr != 0) already HAS an address, so it asks for a unicast reply instead. */
    net_put16_be(&out[10], dhcp_ciaddr ? 0x0000 : 0x8000);
    net_put32_be(&out[12], dhcp_ciaddr);     /* ciaddr: our current address while renewing/rebinding, else 0 */
    /* yiaddr (16), siaddr (20), giaddr (24): all zero, we're not any of those */
    for (int i = 0; i < 6; i++) out[28 + i] = nic.mac[i];  /* chaddr: our hardware address */
    /* sname (44..107), file (108..235): unused, left zero */

    u16 pos = DHCP_FIXED_LEN;
    net_put32_be(&out[pos], DHCP_MAGIC_COOKIE); pos += 4;

    out[pos++] = DHCP_OPT_MSG_TYPE; out[pos++] = 1; out[pos++] = msg_type;

    if (requested_ip) {
        out[pos++] = DHCP_OPT_REQUESTED_IP; out[pos++] = 4;
        net_put32_be(&out[pos], requested_ip); pos += 4;
    }
    if (server_id) {
        out[pos++] = DHCP_OPT_SERVER_ID; out[pos++] = 4;
        net_put32_be(&out[pos], server_id); pos += 4;
    }

    /* Parameter request list: "please also tell me the subnet mask,
     * router, and DNS server while we're here" -- a server is free to
     * ignore any of these, but every server we're likely to meet
     * (a home router, QEMU's SLIRP) happily includes them. */
    out[pos++] = DHCP_OPT_PARAM_REQ; out[pos++] = 3;
    out[pos++] = DHCP_OPT_SUBNET_MASK;
    out[pos++] = DHCP_OPT_ROUTER;
    out[pos++] = DHCP_OPT_DNS;

    out[pos++] = DHCP_OPT_END;
    return pos;
}

static inline void dhcp_send_discover(void) {
    u8 pkt[300];
    u16 len = dhcp_build_packet(pkt, DHCP_MSG_DISCOVER, 0, 0);
#ifdef MW_TEST_DHCP_DROP
    /* TEST ONLY: pretend the first N DISCOVERs were lost on the wire (compile with -DMW_TEST_DHCP_DROP=N) */
    {
        static int dropped = 0;
        if (dropped < MW_TEST_DHCP_DROP) {
            dropped++;
            serial_puts("[DHCP] -> DISCOVER (dropped on purpose by the test hook)\n");
            dhcp_state = DHCP_STATE_DISCOVER_SENT;
            dhcp_last_sent_wall = net_wall_seconds();
            dhcp_last_sent_tick = net_ticks;
            return;
        }
    }
#endif
    serial_puts("[DHCP] -> DISCOVER\n");
    udp_send(0, DHCP_CLIENT_PORT, NET_IP4_BROADCAST, DHCP_SERVER_PORT, pkt, len);
    dhcp_state = DHCP_STATE_DISCOVER_SENT;
    dhcp_last_sent_wall = net_wall_seconds();
    dhcp_last_sent_tick = net_ticks;
}

static inline void dhcp_send_request(u32 requested_ip, u32 server_id) {
    u8 pkt[300];
    u16 len = dhcp_build_packet(pkt, DHCP_MSG_REQUEST, requested_ip, server_id);
    serial_puts("[DHCP] -> REQUEST for ");
    net_log_ip(requested_ip);
    serial_putc('\n');
    /* Still broadcast: other DHCP servers who made competing offers
     * need to see this too, so they know to let their offers expire
     * instead of thinking we ghosted them. */
    udp_send(0, DHCP_CLIENT_PORT, NET_IP4_BROADCAST, DHCP_SERVER_PORT, pkt, len);
    dhcp_state = DHCP_STATE_REQUEST_SENT;
    dhcp_last_sent_wall = net_wall_seconds();
    dhcp_last_sent_tick = net_ticks;
}

/* Walks the TLV option list looking for `want_opt`. Returns 1 and fills
 * out_val (as a big-endian u32, left-padded with zero if the option is
 * shorter than 4 bytes -- fine for the single-byte msg-type option and
 * the 4-byte address options, which are all we ever look for) if found. */
static inline int dhcp_find_option(const u8 *opts, u16 opts_len, u8 want_opt, u32 *out_val) {
    u16 i = 0;
    while (i < opts_len) {
        u8 opt = opts[i++];
        if (opt == DHCP_OPT_END) break;
        if (opt == DHCP_OPT_PAD) continue;   /* pad has no length byte, just skip it */
        if (i >= opts_len) break;
        u8 opt_len = opts[i++];
        if ((u16)(i + opt_len) > opts_len) break;
        if (opt == want_opt) {
            u32 v = 0;
            for (int j = 0; j < opt_len && j < 4; j++) v = (v << 8) | opts[i + j];
            *out_val = v;
            return 1;
        }
        i = (u16)(i + opt_len);
    }
    return 0;
}

/* UDP listener callback -- registered on port 68 (the client port) at
 * startup, so every DHCP server reply lands here regardless of which
 * state we're currently in. */
/* Hands the lease back: forget the address, gateway and DNS (nothing may keep using an address we no longer
 * hold) and start a fresh DISCOVER a second from now. */
static inline void dhcp_drop_lease(const char *why) {
    serial_puts("[DHCP] ");
    serial_puts(why);
    serial_puts(", dropping the lease\n");
    net_cfg.ready = 0;
    net_cfg.my_ip = 0;
    net_cfg.netmask = 0;
    net_cfg.gateway_ip = 0;
    net_cfg.dns_ip = 0;
    dhcp_lease_secs = 0;
    dhcp_ciaddr = 0;
    dhcp_tries = 0;
    dhcp_state = DHCP_STATE_IDLE;                 /* dhcp_poll() starts a fresh DISCOVER a second from now */
    dhcp_last_sent_wall = net_wall_seconds();
    dhcp_last_sent_tick = net_ticks;
}

static inline void dhcp_handle_reply(u32 src_ip, u16 src_port, const u8 *data, u16 len) {
    /* Who is this from, and is it really addressed to this conversation? Every check below used to be
     * missing except the magic cookie and the xid, so any packet that guessed the xid configured the machine. */
    if (src_port != DHCP_SERVER_PORT) return;                         /* replies come from the server port */
    if (len < DHCP_FIXED_LEN + 4) return;
    if (data[0] != DHCP_OP_REPLY || data[1] != DHCP_HTYPE_ETH || data[2] != 6) return;   /* BOOTREPLY over Ethernet */
    if (net_get32_be(&data[DHCP_FIXED_LEN]) != DHCP_MAGIC_COOKIE) return;
    if (net_get32_be(&data[4]) != dhcp_xid) return; /* not our conversation, ignore */
    for (int i = 0; i < 6; i++) if (data[28 + i] != nic.mac[i]) return;   /* chaddr: meant for a different client */

    u32 offered_ip = net_get32_be(&data[16]); /* yiaddr */
    const u8 *opts = data + DHCP_FIXED_LEN + 4;
    u16 opts_len = (u16)(len - DHCP_FIXED_LEN - 4);

    u32 msg_type = 0;
    dhcp_find_option(opts, opts_len, DHCP_OPT_MSG_TYPE, &msg_type);
    u32 server_id = 0;
    int has_server_id = dhcp_find_option(opts, opts_len, DHCP_OPT_SERVER_ID, &server_id);

    if (msg_type == DHCP_MSG_OFFER && dhcp_state == DHCP_STATE_DISCOVER_SENT) {
        if (offered_ip == 0 || offered_ip == NET_IP4_BROADCAST) return;     /* an offer of nothing */
        if (!has_server_id) server_id = src_ip;                             /* RFC 2131 requires option 54; tolerate its absence */
        serial_puts("[DHCP] <- OFFER of ");
        net_log_ip(offered_ip);
        serial_puts(" from server ");
        net_log_ip(server_id);
        serial_putc('\n');
        dhcp_offered_ip = offered_ip;
        dhcp_server_id = server_id;
        dhcp_send_request(offered_ip, server_id);

    } else if (msg_type == DHCP_MSG_ACK && (dhcp_state == DHCP_STATE_REQUEST_SENT ||
                                            dhcp_state == DHCP_STATE_RENEWING || dhcp_state == DHCP_STATE_REBINDING)) {
        int renewing = dhcp_state != DHCP_STATE_REQUEST_SENT;
        /* The ACK must come from the server whose offer we accepted (a REBINDING client may be answered by any
         * server) and must grant exactly the address we asked for / already hold. */
        if (dhcp_state != DHCP_STATE_REBINDING && has_server_id && dhcp_server_id != 0 && server_id != dhcp_server_id) return;
        u32 expect_ip = renewing ? net_cfg.my_ip : dhcp_offered_ip;
        if (offered_ip == 0 || (expect_ip != 0 && offered_ip != expect_ip)) return;

        u32 mask = 0, router = 0, dns = 0, lease = 0;
        int has_mask = dhcp_find_option(opts, opts_len, DHCP_OPT_SUBNET_MASK, &mask);
        int has_router = dhcp_find_option(opts, opts_len, DHCP_OPT_ROUTER, &router);
        int has_dns = dhcp_find_option(opts, opts_len, DHCP_OPT_DNS, &dns);
        int has_lease = dhcp_find_option(opts, opts_len, DHCP_OPT_LEASE_TIME, &lease);

        net_cfg.my_ip = offered_ip;
        if (!renewing || has_mask) net_cfg.netmask = mask;                   /* a renewal that omits an option keeps what we had */
        if (!renewing || has_router) net_cfg.gateway_ip = router;
        if (!renewing || has_dns) net_cfg.dns_ip = dns;
        if (has_server_id) dhcp_server_id = server_id;
        net_cfg.ready = 1;
        dhcp_state = DHCP_STATE_BOUND;
        dhcp_tries = 0;
        dhcp_ciaddr = 0;
        dhcp_lease_secs = has_lease ? lease : 0;
        dhcp_lease_age = 0;
        dhcp_lease_mark = net_wall_seconds();
        dhcp_lease_tick_mark = net_ticks;

        serial_puts(renewing ? "[DHCP] <- ACK, lease renewed for " : "[DHCP] <- ACK, bound to ");
        net_log_ip(net_cfg.my_ip);
        serial_puts(" mask=");
        net_log_ip(net_cfg.netmask);
        serial_puts(" gw=");
        net_log_ip(net_cfg.gateway_ip);
        serial_puts(" dns=");
        net_log_ip(net_cfg.dns_ip);
        serial_puts(" lease=");
        serial_put_dec(has_lease ? lease : 0);
        serial_puts("s\n");

    } else if (msg_type == DHCP_MSG_NAK &&
               (dhcp_state == DHCP_STATE_REQUEST_SENT || dhcp_state == DHCP_STATE_RENEWING || dhcp_state == DHCP_STATE_REBINDING)) {
        /* Only the server we are dealing with can refuse us (a REBINDING client: any). A NAK in any other
         * state used to restart the conversation too -- with a guessable xid that was a one-packet way to
         * knock a bound machine off the network. */
        if (dhcp_state != DHCP_STATE_REBINDING && has_server_id && dhcp_server_id != 0 && server_id != dhcp_server_id) return;
        if (dhcp_state == DHCP_STATE_REQUEST_SENT) {
            /* Server said no to our REQUEST (an offer someone else already snapped up): start over. */
            serial_puts("[DHCP] <- NAK, restarting\n");
            dhcp_state = DHCP_STATE_IDLE;             /* dhcp_poll() starts a fresh DISCOVER a second from now */
            dhcp_last_sent_wall = net_wall_seconds();
            dhcp_last_sent_tick = net_ticks;
        } else {
            dhcp_drop_lease("renewal refused (NAK)");
        }
    }
}

/* Kicks off the DHCP conversation. Call once, after the NIC is up and
 * udp_listen() has a chance to register our callback -- see
 * net_stack_init() in net_stack.h for the actual bring-up order. */
static inline void dhcp_start(void) {
    udp_listen(DHCP_CLIENT_PORT, dhcp_handle_reply);
    dhcp_started = 1;
    dhcp_xid = dhcp_new_xid();
    dhcp_send_discover();
}

/* Retransmission. Call once per main-loop pass (net_stack_poll does).
 *
 * This client used to send ONE DISCOVER at boot and then wait forever -- its own closing comment
 * admitted "if the DISCOVER or REQUEST gets lost, we just sit in that state forever". And a lost
 * first packet is genuinely common: the NIC's link can still be coming up when the kernel's first
 * broadcast goes out, and a hardware-accelerated guest boots far faster than the virtual network
 * behind it. The result was a machine with NO IP address, NO gateway and NO DNS server for the
 * entire session, which the browser could only report as "DNS Lookup Failed ... Tried: 0.0.0.0".
 *
 * Now: an unanswered DISCOVER is resent after 3s, 3s, then every 6s, then every 12s, for as long as
 * it takes (the same transaction id each time, as RFC 2131 permits); an unanswered REQUEST is
 * resent twice and then the whole conversation starts over from DISCOVER; a NAK really does
 * restart. Time is the RTC, not loop passes (netclock.h). */
/* Sends a lease-extension REQUEST. RENEWING: unicast to the server that granted the lease; REBINDING (or
 * if the server's address was never learned): broadcast. ciaddr carries our current address and the
 * requested-IP / server-id options are left out, as RFC 2131 4.3.2 prescribes for these two states. */
static inline void dhcp_send_extension(int broadcast) {
    u8 pkt[300];
    dhcp_ciaddr = net_cfg.my_ip;
    u16 len = dhcp_build_packet(pkt, DHCP_MSG_REQUEST, 0, 0);
    dhcp_ciaddr = 0;
    serial_puts(broadcast ? "[DHCP] -> REQUEST (rebinding, broadcast)\n" : "[DHCP] -> REQUEST (renewing, unicast)\n");
    if (broadcast || dhcp_server_id == 0)
        udp_send(net_cfg.my_ip, DHCP_CLIENT_PORT, NET_IP4_BROADCAST, DHCP_SERVER_PORT, pkt, len);
    else
        udp_send(net_cfg.my_ip, DHCP_CLIENT_PORT, dhcp_server_id, DHCP_SERVER_PORT, pkt, len);
    dhcp_last_sent_wall = net_wall_seconds();
    dhcp_last_sent_tick = net_ticks;
}

/* The lease clock. Runs while we hold an address (BOUND/RENEWING/REBINDING) and the server gave a finite
 * lease: at T1 = lease/2 start renewing, at T2 = 7/8 lease start rebinding, at the full lease time give the
 * address up. While renewing/rebinding the REQUEST is repeated every 30 seconds. */
static inline void dhcp_lease_tick(void) {
    if (dhcp_lease_secs == 0 || dhcp_lease_secs == 0xFFFFFFFFu) return;       /* no lease option / infinite lease */
    if (net_ticks - dhcp_lease_tick_mark < 64u) return;                       /* sample the RTC every so often, not every pass */
    dhcp_lease_tick_mark = net_ticks;

    u32 d = net_wall_elapsed(dhcp_lease_mark);
    if (d == 0) return;
    dhcp_lease_age += d;
    dhcp_lease_mark = net_wall_seconds();

    u32 t1 = dhcp_lease_secs / 2;
    u32 t2 = dhcp_lease_secs - dhcp_lease_secs / 8;
    if (dhcp_lease_age >= dhcp_lease_secs) { dhcp_drop_lease("lease expired"); return; }
    if (dhcp_state == DHCP_STATE_BOUND && dhcp_lease_age >= t1) {
        dhcp_state = DHCP_STATE_RENEWING;
        dhcp_xid = dhcp_new_xid();
        dhcp_send_extension(0);
    } else if (dhcp_state == DHCP_STATE_RENEWING && dhcp_lease_age >= t2) {
        dhcp_state = DHCP_STATE_REBINDING;
        dhcp_xid = dhcp_new_xid();
        dhcp_send_extension(1);
    } else if ((dhcp_state == DHCP_STATE_RENEWING || dhcp_state == DHCP_STATE_REBINDING) &&
               net_wall_elapsed(dhcp_last_sent_wall) >= 30u) {
        dhcp_send_extension(dhcp_state == DHCP_STATE_REBINDING);
    }
}

static inline void dhcp_poll(void) {
    if (!dhcp_started) return;
    if (dhcp_state == DHCP_STATE_BOUND || dhcp_state == DHCP_STATE_RENEWING || dhcp_state == DHCP_STATE_REBINDING) {
        dhcp_lease_tick();
        return;
    }
    u32 waited = net_wall_elapsed(dhcp_last_sent_wall);
    int tick_stale = (net_ticks - dhcp_last_sent_tick) > 200000u;   /* backstop for a stopped RTC */

    if (dhcp_state == DHCP_STATE_IDLE) {
        if (waited >= 1 || tick_stale) {
            dhcp_xid = dhcp_new_xid();
            dhcp_tries = 0;
            dhcp_send_discover();
        }
        return;
    }

    u32 interval = dhcp_tries < 2 ? 3u : dhcp_tries < 4 ? 6u : 12u;
    if (waited < interval && !tick_stale) return;
    dhcp_tries++;

    if (dhcp_state == DHCP_STATE_DISCOVER_SENT) {
        serial_puts("[DHCP] no OFFER yet, resending DISCOVER (retry ");
        serial_put_dec((u32)dhcp_tries);
        serial_puts(")\n");
        dhcp_send_discover();
    } else if (dhcp_state == DHCP_STATE_REQUEST_SENT) {
        if (dhcp_tries >= 3) {
            serial_puts("[DHCP] no ACK, starting over\n");
            dhcp_xid = dhcp_new_xid();
            dhcp_tries = 0;
            dhcp_send_discover();
        } else {
            serial_puts("[DHCP] no ACK yet, resending REQUEST\n");
            dhcp_send_request(dhcp_offered_ip, dhcp_server_id);
        }
    }
}

#endif
