#ifndef ECC_H
#define ECC_H
#include "io.h"

typedef unsigned long long u64; /* the by-now-traditional redundant typedef */

/* ============================================================
 * ecc.h -- elliptic curves for TLS: NIST P-256 (secp256r1) and P-384
 * (secp384r1), with exactly the three operations a TLS *client* needs:
 *
 *   ecdh_keygen()  make an ephemeral key pair            (ClientKeyExchange)
 *   ecdh_shared()  combine our private key with the      (premaster secret)
 *                  server's public point
 *   ecdsa_verify_der()  check a signature                (ServerKeyExchange
 *                  and every ECDSA-signed certificate in the chain)
 *
 * WHY: the old client could only do RSA. But Google Trust Services --
 * which fronts a great many sites -- issues ECDSA P-256 leaf certificates
 * chained through P-384 intermediates and roots, so with RSA-only
 * support an entire class of perfectly ordinary HTTPS sites failed
 * with "untrusted certificate" when the truth was "I can't do that
 * maths."
 *
 * HOW: numbers are little-endian arrays of 32-bit limbs (8 for P-256,
 * 12 for P-384). All modular arithmetic is Montgomery multiplication
 * (CIOS form): it needs only 32x32->64 multiplies, adds and shifts --
 * no division, which this freestanding kernel has none of (no libgcc
 * means no 64-bit divide). Points are Jacobian (X,Y,Z) with x = X/Z^2,
 * y = Y/Z^3, so nothing needs a modular inverse until the very end.
 * Both curves have a = -3, which makes point doubling cheaper.
 *
 * SECURITY NOTES, honestly:
 *  - The scalar multiplication that touches a SECRET (the ephemeral
 *    ECDH key) does a double AND an add for every bit and then picks a
 *    result with a mask, rather than branching on the key bit. That
 *    removes the crudest timing leak, but this is not a vetted
 *    constant-time implementation (the add has data-dependent special
 *    cases that only fire for absurdly unlikely inputs, and 32x32
 *    multiplies aren't guaranteed constant-time on every CPU).
 *    The threat model here: a fresh key per connection, used once.
 *  - Received points are validated (coordinates < p, on the curve)
 *    before use; that is what blocks the invalid-curve attacks.
 *  - ECDSA verification touches only public data, so it takes the fast,
 *    branchy path (Shamir's trick: u1*G + u2*Q in one pass).
 * ============================================================ */

#define ECC_MAX_LIMBS 12

/* Curve constants -- generated by tools/test/gen_ecc_consts.py, which first
 * CHECKS them (G on the curve, n*G = infinity). Little-endian u32 limbs. */
/* P-256 */
#define ECC_P256_P { 0xffffffff, 0xffffffff, 0xffffffff, 0x00000000, 0x00000000, 0x00000000, 0x00000001, 0xffffffff }
#define ECC_P256_N { 0xfc632551, 0xf3b9cac2, 0xa7179e84, 0xbce6faad, 0xffffffff, 0xffffffff, 0x00000000, 0xffffffff }
#define ECC_P256_B { 0x27d2604b, 0x3bce3c3e, 0xcc53b0f6, 0x651d06b0, 0x769886bc, 0xb3ebbd55, 0xaa3a93e7, 0x5ac635d8 }
#define ECC_P256_GX { 0xd898c296, 0xf4a13945, 0x2deb33a0, 0x77037d81, 0x63a440f2, 0xf8bce6e5, 0xe12c4247, 0x6b17d1f2 }
#define ECC_P256_GY { 0x37bf51f5, 0xcbb64068, 0x6b315ece, 0x2bce3357, 0x7c0f9e16, 0x8ee7eb4a, 0xfe1a7f9b, 0x4fe342e2 }
/* P-384 */
#define ECC_P384_P { 0xffffffff, 0x00000000, 0x00000000, 0xffffffff, 0xfffffffe, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff }
#define ECC_P384_N { 0xccc52973, 0xecec196a, 0x48b0a77a, 0x581a0db2, 0xf4372ddf, 0xc7634d81, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff }
#define ECC_P384_B { 0xd3ec2aef, 0x2a85c8ed, 0x8a2ed19d, 0xc656398d, 0x5013875a, 0x0314088f, 0xfe814112, 0x181d9c6e, 0xe3f82d19, 0x988e056b, 0xe23ee7e4, 0xb3312fa7 }
#define ECC_P384_GX { 0x72760ab7, 0x3a545e38, 0xbf55296c, 0x5502f25d, 0x82542a38, 0x59f741e0, 0x8ba79b98, 0x6e1d3b62, 0xf320ad74, 0x8eb1c71e, 0xbe8b0537, 0xaa87ca22 }
#define ECC_P384_GY { 0x90ea0e5f, 0x7a431d7c, 0x1d7e819d, 0x0a60b1ce, 0xb5f0b8c0, 0xe9da3113, 0x289a147c, 0xf8f41dbd, 0x9292dc29, 0x5d9e98bf, 0x96262c6f, 0x3617de4a }

typedef struct {
    int n;               /* limbs: 8 (P-256) or 12 (P-384) */
    int bytes;           /* 32 or 48: size of a coordinate / scalar in bytes */
    u16 group_id;        /* TLS "named group" number: 23 = secp256r1, 24 = secp384r1 */
    u32 p[ECC_MAX_LIMBS], order[ECC_MAX_LIMBS], b[ECC_MAX_LIMBS];
    u32 gx[ECC_MAX_LIMBS], gy[ECC_MAX_LIMBS];
    /* derived once, lazily, by ecc_curve_prepare(): */
    int ready;
    u32 p_m0, n_m0;                       /* -m^-1 mod 2^32 for Montgomery reduction */
    u32 p_rr[ECC_MAX_LIMBS], n_rr[ECC_MAX_LIMBS];   /* R^2 mod m, to convert INTO Montgomery form */
    u32 p_one[ECC_MAX_LIMBS];             /* 1 in Montgomery form (= R mod p) */
} ecc_curve_t;

static ecc_curve_t ecc_p256 = { .n = 8, .bytes = 32, .group_id = 23,
    .p = ECC_P256_P, .order = ECC_P256_N, .b = ECC_P256_B, .gx = ECC_P256_GX, .gy = ECC_P256_GY };
static ecc_curve_t ecc_p384 = { .n = 12, .bytes = 48, .group_id = 24,
    .p = ECC_P384_P, .order = ECC_P384_N, .b = ECC_P384_B, .gx = ECC_P384_GX, .gy = ECC_P384_GY };

/* ---------- plain multi-limb helpers (n limbs, little-endian) ---------- */

static inline int ecc_is_zero(const u32 *a, int n) {
    u32 acc = 0;
    for (int i = 0; i < n; i++) acc |= a[i];
    return acc == 0;
}
static inline int ecc_cmp(const u32 *a, const u32 *b, int n) {
    for (int i = n - 1; i >= 0; i--) {
        if (a[i] != b[i]) return a[i] > b[i] ? 1 : -1;
    }
    return 0;
}
static inline void ecc_copy(u32 *r, const u32 *a, int n) { for (int i = 0; i < n; i++) r[i] = a[i]; }
static inline void ecc_zero(u32 *r, int n) { for (int i = 0; i < n; i++) r[i] = 0; }

/* r = a + b, returns the carry out. r may alias a or b. */
static inline u32 ecc_add_raw(u32 *r, const u32 *a, const u32 *b, int n) {
    u64 c = 0;
    for (int i = 0; i < n; i++) { u64 s = (u64)a[i] + b[i] + c; r[i] = (u32)s; c = s >> 32; }
    return (u32)c;
}
/* r = a - b, returns the borrow out (1 if a < b). r may alias a or b. */
static inline u32 ecc_sub_raw(u32 *r, const u32 *a, const u32 *b, int n) {
    u64 br = 0;
    for (int i = 0; i < n; i++) {
        u64 d = (u64)a[i] - b[i] - br;
        r[i] = (u32)d;
        br = (d >> 32) & 1;
    }
    return (u32)br;
}

/* big-endian bytes <-> limbs. from_be zero-pads on the left. */
static inline void ecc_from_be(u32 *r, int n, const u8 *be, int len) {
    ecc_zero(r, n);
    for (int i = 0; i < len; i++) {
        int bitpos = (len - 1 - i);          /* byte index from the least significant end */
        r[bitpos / 4] |= (u32)be[i] << (8 * (bitpos % 4));
    }
}
static inline void ecc_to_be(u8 *be, int len, const u32 *a) {
    for (int i = 0; i < len; i++) {
        int bitpos = (len - 1 - i);
        be[i] = (u8)(a[bitpos / 4] >> (8 * (bitpos % 4)));
    }
}

/* ---------- Montgomery field arithmetic modulo m (p or the order n) ---------- */

typedef struct { const u32 *m; u32 m0; const u32 *rr; int n; } ecc_field_t;

/* r = a * b * R^-1 mod m, where R = 2^(32n). CIOS Montgomery multiplication. */
static inline void ecc_mm(const ecc_field_t *f, u32 *r, const u32 *a, const u32 *b) {
    int n = f->n;
    u32 t[ECC_MAX_LIMBS + 2];
    for (int i = 0; i < n + 2; i++) t[i] = 0;
    for (int i = 0; i < n; i++) {
        u64 c = 0;
        for (int j = 0; j < n; j++) {
            u64 s = (u64)t[j] + (u64)a[j] * b[i] + c;
            t[j] = (u32)s; c = s >> 32;
        }
        u64 s = (u64)t[n] + c;
        t[n] = (u32)s; t[n + 1] = (u32)(s >> 32);

        u32 mq = t[0] * f->m0;
        c = ((u64)t[0] + (u64)mq * f->m[0]) >> 32;
        for (int j = 1; j < n; j++) {
            s = (u64)t[j] + (u64)mq * f->m[j] + c;
            t[j - 1] = (u32)s; c = s >> 32;
        }
        s = (u64)t[n] + c;
        t[n - 1] = (u32)s;
        t[n] = t[n + 1] + (u32)(s >> 32);
    }
    /* t < 2m: one conditional subtraction finishes the reduction */
    u32 tmp[ECC_MAX_LIMBS];
    u32 borrow = ecc_sub_raw(tmp, t, f->m, n);
    if (t[n] != 0 || !borrow) ecc_copy(r, tmp, n); else ecc_copy(r, t, n);
}
static inline void ecc_ma(const ecc_field_t *f, u32 *r, const u32 *a, const u32 *b) {
    u32 t[ECC_MAX_LIMBS];
    u32 carry = ecc_add_raw(t, a, b, f->n);
    u32 u[ECC_MAX_LIMBS];
    u32 borrow = ecc_sub_raw(u, t, f->m, f->n);
    if (carry || !borrow) ecc_copy(r, u, f->n); else ecc_copy(r, t, f->n);
}
static inline void ecc_ms(const ecc_field_t *f, u32 *r, const u32 *a, const u32 *b) {
    u32 t[ECC_MAX_LIMBS];
    u32 borrow = ecc_sub_raw(t, a, b, f->n);
    if (borrow) ecc_add_raw(t, t, f->m, f->n);
    ecc_copy(r, t, f->n);
}
static inline void ecc_to_mont(const ecc_field_t *f, u32 *r, const u32 *a) { ecc_mm(f, r, a, f->rr); }
static inline void ecc_from_mont(const ecc_field_t *f, u32 *r, const u32 *a) {
    u32 one[ECC_MAX_LIMBS]; ecc_zero(one, f->n); one[0] = 1;
    ecc_mm(f, r, a, one);
}

/* r = a^-1 mod m via Fermat (a^(m-2)); a and r in Montgomery form, m prime. */
static inline void ecc_minv(const ecc_field_t *f, u32 *r, const u32 *a, const u32 *one_m) {
    int n = f->n;
    u32 e[ECC_MAX_LIMBS];
    ecc_copy(e, f->m, n);
    u32 two[ECC_MAX_LIMBS]; ecc_zero(two, n); two[0] = 2;
    ecc_sub_raw(e, e, two, n);                 /* e = m - 2 */
    u32 acc[ECC_MAX_LIMBS];
    ecc_copy(acc, one_m, n);
    for (int i = n * 32 - 1; i >= 0; i--) {
        ecc_mm(f, acc, acc, acc);
        if ((e[i / 32] >> (i % 32)) & 1) ecc_mm(f, acc, acc, a);
    }
    ecc_copy(r, acc, n);
}

/* -m^-1 mod 2^32 by Newton iteration (each step doubles the correct bits). */
static inline u32 ecc_neg_inv32(u32 m0) {
    u32 x = m0;                       /* correct to 3 bits for any odd m0 */
    for (int i = 0; i < 5; i++) x *= 2 - m0 * x;
    return (u32)0 - x;
}

/* R^2 mod m by doubling 1 a total of 64n times, reducing each time. */
static inline void ecc_compute_rr(u32 *rr, u32 *r_mod_m, const u32 *m, int n) {
    u32 x[ECC_MAX_LIMBS]; ecc_zero(x, n); x[0] = 1;
    for (int i = 0; i < 64 * n; i++) {
        u32 carry = ecc_add_raw(x, x, x, n);
        u32 t[ECC_MAX_LIMBS];
        u32 borrow = ecc_sub_raw(t, x, m, n);
        if (carry || !borrow) ecc_copy(x, t, n);
        if (i == 32 * n - 1 && r_mod_m) ecc_copy(r_mod_m, x, n);   /* halfway: 2^(32n) mod m = R mod m */
    }
    ecc_copy(rr, x, n);
}

static inline void ecc_curve_prepare(ecc_curve_t *c) {
    if (c->ready) return;
    c->p_m0 = ecc_neg_inv32(c->p[0]);
    c->n_m0 = ecc_neg_inv32(c->order[0]);
    ecc_compute_rr(c->p_rr, c->p_one, c->p, c->n);
    u32 dummy[ECC_MAX_LIMBS];
    ecc_compute_rr(c->n_rr, dummy, c->order, c->n);
    c->ready = 1;
}
static inline ecc_field_t ecc_fp(const ecc_curve_t *c) { ecc_field_t f = { c->p, c->p_m0, c->p_rr, c->n }; return f; }
static inline ecc_field_t ecc_fn(const ecc_curve_t *c) { ecc_field_t f = { c->order, c->n_m0, c->n_rr, c->n }; return f; }

/* ---------- Jacobian points, coordinates in Montgomery form mod p ---------- */

typedef struct { u32 x[ECC_MAX_LIMBS], y[ECC_MAX_LIMBS], z[ECC_MAX_LIMBS]; } ecc_point_t;

static inline int ecc_pt_is_inf(const ecc_point_t *p, int n) { return ecc_is_zero(p->z, n); }
static inline void ecc_pt_set_inf(ecc_point_t *p, const ecc_curve_t *c) {
    ecc_zero(p->x, c->n); ecc_copy(p->y, c->p_one, c->n); ecc_zero(p->z, c->n);
}

/* out = 2 * a  (dbl-2001-b, valid because the curve has a = -3) */
static inline void ecc_pt_dbl(const ecc_curve_t *c, ecc_point_t *out, const ecc_point_t *a) {
    ecc_field_t f = ecc_fp(c);
    if (ecc_pt_is_inf(a, c->n) || ecc_is_zero(a->y, c->n)) { ecc_pt_set_inf(out, c); return; }
    u32 delta[ECC_MAX_LIMBS], gamma[ECC_MAX_LIMBS], beta[ECC_MAX_LIMBS], alpha[ECC_MAX_LIMBS];
    u32 t1[ECC_MAX_LIMBS], t2[ECC_MAX_LIMBS], x3[ECC_MAX_LIMBS], y3[ECC_MAX_LIMBS], z3[ECC_MAX_LIMBS];

    ecc_mm(&f, delta, a->z, a->z);            /* delta = Z^2 */
    ecc_mm(&f, gamma, a->y, a->y);            /* gamma = Y^2 */
    ecc_mm(&f, beta, a->x, gamma);            /* beta = X*gamma */
    ecc_ms(&f, t1, a->x, delta);              /* X - delta */
    ecc_ma(&f, t2, a->x, delta);              /* X + delta */
    ecc_mm(&f, alpha, t1, t2);
    ecc_ma(&f, t1, alpha, alpha);
    ecc_ma(&f, alpha, t1, alpha);             /* alpha = 3*(X-delta)*(X+delta) */

    ecc_mm(&f, t1, alpha, alpha);             /* alpha^2 */
    ecc_ma(&f, t2, beta, beta);               /* 2beta */
    ecc_ma(&f, t2, t2, t2);                   /* 4beta */
    ecc_ma(&f, x3, t2, t2);                   /* 8beta */
    ecc_ms(&f, x3, t1, x3);                   /* X3 = alpha^2 - 8beta */

    ecc_ma(&f, t1, a->y, a->z);
    ecc_mm(&f, t1, t1, t1);                   /* (Y+Z)^2 */
    ecc_ms(&f, t1, t1, gamma);
    ecc_ms(&f, z3, t1, delta);                /* Z3 = (Y+Z)^2 - gamma - delta */

    ecc_ms(&f, t1, t2, x3);                   /* 4beta - X3 */
    ecc_mm(&f, t1, alpha, t1);
    ecc_mm(&f, t2, gamma, gamma);             /* gamma^2 */
    ecc_ma(&f, t2, t2, t2); ecc_ma(&f, t2, t2, t2); ecc_ma(&f, t2, t2, t2);   /* 8gamma^2 */
    ecc_ms(&f, y3, t1, t2);                   /* Y3 = alpha*(4beta - X3) - 8gamma^2 */

    ecc_copy(out->x, x3, c->n); ecc_copy(out->y, y3, c->n); ecc_copy(out->z, z3, c->n);
}

/* out = a + b  (add-2007-bl), with the special cases handled: either
 * input at infinity, a == b (falls back to doubling), a == -b (infinity). */
static inline void ecc_pt_add(const ecc_curve_t *c, ecc_point_t *out, const ecc_point_t *a, const ecc_point_t *b) {
    ecc_field_t f = ecc_fp(c);
    int n = c->n;
    if (ecc_pt_is_inf(a, n)) { *out = *b; return; }
    if (ecc_pt_is_inf(b, n)) { *out = *a; return; }

    u32 z1z1[ECC_MAX_LIMBS], z2z2[ECC_MAX_LIMBS], u1[ECC_MAX_LIMBS], u2[ECC_MAX_LIMBS];
    u32 s1[ECC_MAX_LIMBS], s2[ECC_MAX_LIMBS], h[ECC_MAX_LIMBS], i2[ECC_MAX_LIMBS], j[ECC_MAX_LIMBS];
    u32 r[ECC_MAX_LIMBS], v[ECC_MAX_LIMBS], t[ECC_MAX_LIMBS], x3[ECC_MAX_LIMBS], y3[ECC_MAX_LIMBS], z3[ECC_MAX_LIMBS];

    ecc_mm(&f, z1z1, a->z, a->z);
    ecc_mm(&f, z2z2, b->z, b->z);
    ecc_mm(&f, u1, a->x, z2z2);
    ecc_mm(&f, u2, b->x, z1z1);
    ecc_mm(&f, t, b->z, z2z2); ecc_mm(&f, s1, a->y, t);      /* S1 = Y1*Z2^3 */
    ecc_mm(&f, t, a->z, z1z1); ecc_mm(&f, s2, b->y, t);      /* S2 = Y2*Z1^3 */

    ecc_ms(&f, h, u2, u1);
    ecc_ms(&f, r, s2, s1);
    if (ecc_is_zero(h, n)) {
        if (ecc_is_zero(r, n)) { ecc_pt_dbl(c, out, a); }     /* same point */
        else { ecc_pt_set_inf(out, c); }                      /* P + (-P) */
        return;
    }
    ecc_ma(&f, r, r, r);                                      /* r = 2(S2-S1) */
    ecc_ma(&f, t, h, h);
    ecc_mm(&f, i2, t, t);                                     /* I = (2H)^2 */
    ecc_mm(&f, j, h, i2);                                     /* J = H*I */
    ecc_mm(&f, v, u1, i2);                                    /* V = U1*I */

    ecc_mm(&f, x3, r, r);
    ecc_ms(&f, x3, x3, j);
    ecc_ma(&f, t, v, v);
    ecc_ms(&f, x3, x3, t);                                    /* X3 = r^2 - J - 2V */

    ecc_ms(&f, t, v, x3);
    ecc_mm(&f, y3, r, t);
    ecc_mm(&f, t, s1, j);
    ecc_ma(&f, t, t, t);
    ecc_ms(&f, y3, y3, t);                                    /* Y3 = r(V-X3) - 2*S1*J */

    ecc_ma(&f, t, a->z, b->z);
    ecc_mm(&f, t, t, t);
    ecc_ms(&f, t, t, z1z1);
    ecc_ms(&f, t, t, z2z2);
    ecc_mm(&f, z3, t, h);                                     /* Z3 = ((Z1+Z2)^2 - Z1Z1 - Z2Z2)*H */

    ecc_copy(out->x, x3, n); ecc_copy(out->y, y3, n); ecc_copy(out->z, z3, n);
}

/* dst = mask ? src : dst, with mask 0 or 0xFFFFFFFF -- no branch on the secret bit. */
static inline void ecc_pt_cmov(ecc_point_t *dst, const ecc_point_t *src, u32 mask, int n) {
    for (int i = 0; i < n; i++) {
        dst->x[i] = (dst->x[i] & ~mask) | (src->x[i] & mask);
        dst->y[i] = (dst->y[i] & ~mask) | (src->y[i] & mask);
        dst->z[i] = (dst->z[i] & ~mask) | (src->z[i] & mask);
    }
}

/* out = k * P, k a plain (non-Montgomery) n-limb scalar. Double-and-ALWAYS-add:
 * every bit does both operations and the result is selected by mask -- this
 * is the variant used for secret scalars. */
static inline void ecc_scalar_mul(const ecc_curve_t *c, ecc_point_t *out, const u32 *k, const ecc_point_t *p) {
    int n = c->n;
    ecc_point_t r, sum;
    ecc_pt_set_inf(&r, c);
    for (int i = n * 32 - 1; i >= 0; i--) {
        ecc_pt_dbl(c, &r, &r);
        ecc_pt_add(c, &sum, &r, p);
        u32 mask = (u32)0 - ((k[i / 32] >> (i % 32)) & 1);
        ecc_pt_cmov(&r, &sum, mask, n);
    }
    *out = r;
}

/* Jacobian (Montgomery) -> affine, plain (non-Montgomery) big integers. 0 if at infinity. */
static inline int ecc_to_affine(const ecc_curve_t *c, u32 *x, u32 *y, const ecc_point_t *p) {
    ecc_field_t f = ecc_fp(c);
    int n = c->n;
    if (ecc_pt_is_inf(p, n)) return 0;
    u32 zi[ECC_MAX_LIMBS], zi2[ECC_MAX_LIMBS], zi3[ECC_MAX_LIMBS], t[ECC_MAX_LIMBS];
    ecc_minv(&f, zi, p->z, c->p_one);
    ecc_mm(&f, zi2, zi, zi);
    ecc_mm(&f, zi3, zi2, zi);
    if (x) { ecc_mm(&f, t, p->x, zi2); ecc_from_mont(&f, x, t); }
    if (y) { ecc_mm(&f, t, p->y, zi3); ecc_from_mont(&f, y, t); }
    return 1;
}

/* Loads an affine point (plain integers) into Jacobian/Montgomery form, and CHECKS
 * it: both coordinates < p, and y^2 = x^3 - 3x + b. This check is what stands
 * between us and an "invalid curve" attack, so it is not optional. */
static inline int ecc_pt_load_checked(const ecc_curve_t *c, ecc_point_t *out, const u32 *x, const u32 *y) {
    ecc_field_t f = ecc_fp(c);
    int n = c->n;
    if (ecc_cmp(x, c->p, n) >= 0 || ecc_cmp(y, c->p, n) >= 0) return 0;
    u32 xm[ECC_MAX_LIMBS], ym[ECC_MAX_LIMBS], bm[ECC_MAX_LIMBS];
    u32 lhs[ECC_MAX_LIMBS], rhs[ECC_MAX_LIMBS], t[ECC_MAX_LIMBS];
    ecc_to_mont(&f, xm, x); ecc_to_mont(&f, ym, y); ecc_to_mont(&f, bm, c->b);
    ecc_mm(&f, lhs, ym, ym);                       /* y^2 */
    ecc_mm(&f, rhs, xm, xm);
    ecc_mm(&f, rhs, rhs, xm);                      /* x^3 */
    ecc_ma(&f, t, xm, xm); ecc_ma(&f, t, t, xm);  /* 3x */
    ecc_ms(&f, rhs, rhs, t);
    ecc_ma(&f, rhs, rhs, bm);                      /* x^3 - 3x + b */
    if (ecc_cmp(lhs, rhs, n) != 0) return 0;
    ecc_copy(out->x, xm, n); ecc_copy(out->y, ym, n); ecc_copy(out->z, c->p_one, n);
    return 1;
}

/* Parses an uncompressed SEC1 point (0x04 || X || Y) and validates it. */
static inline int ecc_parse_point(const ecc_curve_t *c, ecc_point_t *out, const u8 *buf, u32 len) {
    if (len != (u32)(1 + 2 * c->bytes) || buf[0] != 0x04) return 0;
    u32 x[ECC_MAX_LIMBS] = {0}, y[ECC_MAX_LIMBS] = {0};
    ecc_from_be(x, c->n, buf + 1, c->bytes);
    ecc_from_be(y, c->n, buf + 1 + c->bytes, c->bytes);
    return ecc_pt_load_checked(c, out, x, y);
}

static inline void ecc_base_point(const ecc_curve_t *c, ecc_point_t *g) {
    ecc_field_t f = ecc_fp(c);
    ecc_to_mont(&f, g->x, c->gx);
    ecc_to_mont(&f, g->y, c->gy);
    ecc_copy(g->z, c->p_one, c->n);
}

/* ---------- ECDH ---------- */

/* Makes an ephemeral key pair from `bytes` random bytes (the caller supplies
 * them -- see tls.h's PRNG). priv = the random value with its top bit forced
 * on (a fixed bit length keeps the scalar multiply's shape uniform), reduced
 * once mod the group order in the ~2^-32 case it landed above it.
 * Writes the private scalar (big-endian, `bytes` long) and the public point
 * (0x04||X||Y, 1+2*bytes long). Returns 0 only if the result is unusable. */
static inline int ecdh_keygen(ecc_curve_t *c, const u8 *rand_bytes, u8 *priv_out, u8 *pub_out) {
    ecc_curve_prepare(c);
    u32 k[ECC_MAX_LIMBS];
    ecc_from_be(k, c->n, rand_bytes, c->bytes);
    k[c->n - 1] |= 0x80000000u;
    if (ecc_cmp(k, c->order, c->n) >= 0) ecc_sub_raw(k, k, c->order, c->n);
    if (ecc_is_zero(k, c->n)) return 0;

    ecc_point_t g, q;
    ecc_base_point(c, &g);
    ecc_scalar_mul(c, &q, k, &g);
    u32 x[ECC_MAX_LIMBS], y[ECC_MAX_LIMBS];
    if (!ecc_to_affine(c, x, y, &q)) return 0;

    ecc_to_be(priv_out, c->bytes, k);
    pub_out[0] = 0x04;
    ecc_to_be(pub_out + 1, c->bytes, x);
    ecc_to_be(pub_out + 1 + c->bytes, c->bytes, y);
    return 1;
}

/* Computes the shared secret: the X coordinate of (priv * peer_point), big-endian,
 * `bytes` long -- which is exactly the ECDHE premaster secret TLS wants.
 * Returns 0 if the peer's point is malformed / not on the curve / gives infinity. */
static inline int ecdh_shared(ecc_curve_t *c, const u8 *priv, const u8 *peer_pub, u32 peer_len, u8 *secret_out) {
    ecc_curve_prepare(c);
    ecc_point_t q, r;
    if (!ecc_parse_point(c, &q, peer_pub, peer_len)) return 0;
    u32 k[ECC_MAX_LIMBS];
    ecc_from_be(k, c->n, priv, c->bytes);
    ecc_scalar_mul(c, &r, k, &q);
    u32 x[ECC_MAX_LIMBS];
    if (!ecc_to_affine(c, x, 0, &r)) return 0;
    ecc_to_be(secret_out, c->bytes, x);
    return 1;
}

/* ---------- ECDSA verification ---------- */

/* Minimal DER reader for one length: returns bytes consumed for the length field, 0 on error. */
static inline u32 ecc_der_len(const u8 *p, u32 avail, u32 *len_out) {
    if (avail < 1) return 0;
    if (p[0] < 0x80) { *len_out = p[0]; return 1; }
    u32 nb = p[0] & 0x7F;
    if (nb == 0 || nb > 2 || avail < 1 + nb) return 0;
    u32 l = 0;
    for (u32 i = 0; i < nb; i++) l = (l << 8) | p[1 + i];
    *len_out = l;
    return 1 + nb;
}

/* Reads one DER INTEGER into limbs (strips leading zero bytes; rejects > `bytes` significant
 * bytes and negative values). Advances *pos. */
static inline int ecc_der_uint(const ecc_curve_t *c, u32 *limbs, const u8 *buf, u32 len, u32 *pos) {
    if (*pos >= len || buf[*pos] != 0x02) return 0;
    u32 l, hl = ecc_der_len(buf + *pos + 1, len - *pos - 1, &l);
    if (!hl) return 0;
    u32 start = *pos + 1 + hl;
    if (l == 0 || start + l > len) return 0;
    const u8 *v = buf + start;
    if (v[0] & 0x80) return 0;                       /* negative */
    while (l > 1 && v[0] == 0) { v++; l--; }
    if (l > (u32)c->bytes) return 0;
    ecc_from_be(limbs, c->n, v, (int)l);
    *pos = (u32)((v + l) - buf);      /* one past this INTEGER's last content byte */
    return 1;
}

/* Verifies an ECDSA signature (DER: SEQUENCE { INTEGER r, INTEGER s }) over `hash`
 * (the already-computed digest; any length -- it is truncated/padded to the curve's
 * order size as SEC1 4.1.4 says) against the public key `pub` (uncompressed point).
 * Returns 1 only if the signature is valid. */
static inline int ecdsa_verify_der(ecc_curve_t *c, const u8 *pub, u32 pub_len,
                                   const u8 *hash, u32 hash_len,
                                   const u8 *sig, u32 sig_len) {
    ecc_curve_prepare(c);
    int n = c->n;
    ecc_field_t fn = ecc_fn(c);

    /* --- parse the signature --- */
    u32 r[ECC_MAX_LIMBS], s[ECC_MAX_LIMBS];
    if (sig_len < 8 || sig[0] != 0x30) return 0;
    u32 seq_len, hl = ecc_der_len(sig + 1, sig_len - 1, &seq_len);
    if (!hl || 1 + hl + seq_len != sig_len) return 0;
    u32 pos = 1 + hl;
    if (!ecc_der_uint(c, r, sig, sig_len, &pos)) return 0;
    if (!ecc_der_uint(c, s, sig, sig_len, &pos)) return 0;
    if (pos != sig_len) return 0;
    if (ecc_is_zero(r, n) || ecc_cmp(r, c->order, n) >= 0) return 0;
    if (ecc_is_zero(s, n) || ecc_cmp(s, c->order, n) >= 0) return 0;

    /* --- the public key must be a valid point on the curve --- */
    ecc_point_t q, g;
    if (!ecc_parse_point(c, &q, pub, pub_len)) return 0;
    ecc_base_point(c, &g);

    /* --- e = leftmost `bytes` bytes of the hash, as an integer, reduced mod order --- */
    u32 e[ECC_MAX_LIMBS];
    u32 use = hash_len > (u32)c->bytes ? (u32)c->bytes : hash_len;
    ecc_from_be(e, n, hash, (int)use);
    if (ecc_cmp(e, c->order, n) >= 0) ecc_sub_raw(e, e, c->order, n);

    /* --- w = s^-1 mod order;  u1 = e*w;  u2 = r*w  (mod order) --- */
    u32 sm[ECC_MAX_LIMBS], wm[ECC_MAX_LIMBS], u1[ECC_MAX_LIMBS], u2[ECC_MAX_LIMBS], one_n[ECC_MAX_LIMBS];
    ecc_zero(one_n, n); one_n[0] = 1;
    ecc_to_mont(&fn, one_n, one_n);                  /* 1 in Montgomery form mod order */
    ecc_to_mont(&fn, sm, s);
    ecc_minv(&fn, wm, sm, one_n);                    /* wm = w*R */
    ecc_mm(&fn, u1, e, wm);                          /* e * (wR) * R^-1 = e*w */
    ecc_mm(&fn, u2, r, wm);

    /* --- P = u1*G + u2*Q by Shamir's trick (public data: branches are fine) --- */
    ecc_point_t gq, acc;
    ecc_pt_add(c, &gq, &g, &q);
    ecc_pt_set_inf(&acc, c);
    for (int i = n * 32 - 1; i >= 0; i--) {
        ecc_pt_dbl(c, &acc, &acc);
        u32 b1 = (u1[i / 32] >> (i % 32)) & 1, b2 = (u2[i / 32] >> (i % 32)) & 1;
        if (b1 && b2) ecc_pt_add(c, &acc, &acc, &gq);
        else if (b1)  ecc_pt_add(c, &acc, &acc, &g);
        else if (b2)  ecc_pt_add(c, &acc, &acc, &q);
    }
    u32 x[ECC_MAX_LIMBS];
    if (!ecc_to_affine(c, x, 0, &acc)) return 0;
    if (ecc_cmp(x, c->order, n) >= 0) ecc_sub_raw(x, x, c->order, n);   /* x mod order (p < 2*order, so once is enough) */
    return ecc_cmp(x, r, n) == 0;
}

static inline ecc_curve_t *ecc_curve_by_group(u16 group_id) {
    if (group_id == 23) return &ecc_p256;
    if (group_id == 24) return &ecc_p384;
    return 0;
}

#endif
